### ISSUE TITLE
Feature Request: Would it be possible to install version from GIT given a commit hash?

### ISSUE THREAD

**Issue by Xliff** [skaji/rakuenv#2]
Is this a planned item in the roadmap? If not, I'd like to officially suggest it.

**Comment by skaji** [comment]
yes.

**Comment by Xliff** [comment]
Great! If you would like testers or even help with the implementation, I would be happy to contribute!

**Comment by skaji** [comment]
It's already implemented. See `p6env install --help`.

**Comment by Xliff** [comment]
\o/
