### ISSUE TITLE
Integration with Whateverable?

### ISSUE THREAD

**Issue by AlexDaniel** [skaji/rakuenv#3]
Given that https://github.com/skaji/p6env/issues/2 is now resolved, there's an opportunity to speed it up.

See https://github.com/perl6/whateverable/wiki/Shareable for some info.

Basically, you can go to https://whateverable.6lang.org/f583f22 (where f583f22 is any rakudo commit) and it will give you an archive. All rakudo revisions since 2014.01 are available. Using that archive is a bit tricky (because rakudo is not relocatable, and also due to specifics of how these archives are created). My understanding is that people only want to switch to specific commits for development purposes, and speeding that up can be kinda cool.

**Comment by skaji** [comment]
Thanks. I think this may be implemented by a plugin.
