### ISSUE TITLE
Where do binaries go to?

### ISSUE THREAD

**Issue by MattOates** [skaji/rakuenv#4]
Installing Cro with Zef from the p6env I cannot find the `cro` executable tool anywhere and a rehash does not present it shimmed into my path? This was a feature that did work in rakudobrew and is a bit of a blocker. Everything else works great in p6env for me, so thanks for your efforts so far!

**Comment by skaji** [comment]
Please follow this comment http://blogs.perl.org/users/shoichi_kaji1/2019/01/p6env.html#comment-1805451

**Comment by MattOates** [comment]
I suspect I did a `zef install Cro` instead of `zef install cro` firs time around. Everything looks fine and other modules with CLI install ok. Sorry for being an idiot  🤦‍♂️
